/// A snapshot of the question bank that previously lived as static lists
/// in text_strings.dart, reshaped as {category label: [questions]} so
/// ManageQuestionsScreen can push it into Firestore with one tap.
///
/// This file is only used once (by "Import bank" in the admin Questions
/// screen). After migrating, Firestore is the source of truth — you can
/// delete this file and the old static lists in text_strings.dart once
/// you've confirmed everything imported correctly.
const Map<String, List<String>> legacyQuestionBank = {
  'Generic Interview': [
    "Tell me about yourself and your professional background.",
    "Why are you interested in this role?",
    "What are your greatest strengths relevant to this position?",
    "Describe a challenging project you worked on and how you handled it.",
    "How do you prioritize tasks when working under a deadline?",
    "Tell me about a time you disagreed with a teammate. How was it resolved?",
    "Where do you see yourself professionally in the next few years?",
    "What tools or technologies do you use daily in this field?",
    "How do you handle feedback or criticism on your work?",
    "Do you have any questions for us about the role or the team?",
  ],
  'Software Engineer': [
    "Walk me through how you approach debugging a production issue.",
    "Explain the difference between a stack and a queue with an example.",
    "How would you design a scalable REST API for a growing app?",
    "Describe a time you had to refactor messy legacy code.",
    "What is the difference between synchronous and asynchronous code?",
    "How do you ensure code quality in a team project?",
    "Explain the concept of Big-O notation with a simple example.",
    "How do you approach writing unit tests for new features?",
    "Tell me about a bug that was hard to reproduce and how you found it.",
    "What version control practices do you follow in a team?",
  ],
  'Data Analyst': [
    "How do you handle missing or inconsistent data in a dataset?",
    "Explain the difference between INNER JOIN and LEFT JOIN with an example.",
    "How would you present a complex dataset to a non-technical stakeholder?",
    "What steps do you take to validate the accuracy of your analysis?",
    "Describe a time your analysis directly influenced a business decision.",
    "Which visualization would you choose to show a trend over time, and why?",
    "How do you decide which metrics matter most for a given business problem?",
    "Explain the difference between correlation and causation.",
    "How do you handle a stakeholder who disagrees with your findings?",
    "What tools do you use for data cleaning and reporting?",
  ],
  'Machine Learning': [
    "Explain the difference between supervised and unsupervised learning.",
    "How do you handle overfitting in a machine learning model?",
    "What is the bias-variance tradeoff?",
    "Walk me through your process for evaluating a classification model.",
    "How would you handle an imbalanced dataset?",
    "Explain how a decision tree makes predictions.",
    "What is the purpose of a validation set versus a test set?",
    "Describe a machine learning project you're proud of, end-to-end.",
    "How do you decide which algorithm to try first for a new problem?",
    "How would you explain a model's prediction to a non-technical manager?",
  ],
  'Full Stack Developer': [
    "How do you manage state between the frontend and backend of an app?",
    "Explain how you would secure a REST API endpoint.",
    "Describe your process for turning a UI design into working code.",
    "How do you handle version conflicts when merging branches?",
    "What is your approach to optimizing a slow-loading web page?",
    "How would you structure a full-stack project from scratch?",
    "Explain the role of a database index and when you'd add one.",
    "How do you keep the frontend and backend in sync during development?",
    "Describe a bug that spanned both frontend and backend. How did you fix it?",
    "What's your approach to deploying a full-stack application?",
  ],
  'Digital Marketing': [
    "How do you measure the success of a digital marketing campaign?",
    "Describe a campaign you ran that didn't perform well. What did you learn?",
    "How do you decide which platform to prioritize for a new product?",
    "What is your approach to keyword research for SEO?",
    "How do you allocate budget across multiple ad campaigns?",
    "Explain how you would improve a landing page's conversion rate.",
    "How do you stay updated with changing marketing trends?",
    "Describe how you'd build a content calendar for a brand.",
    "How do you handle negative feedback or reviews online?",
    "What metrics matter most to you when reporting to a client?",
  ],
  'Social Media Manager': [
    "How do you plan a content calendar across multiple platforms?",
    "Describe how you'd grow engagement for a brand with a small following.",
    "How do you handle a social media crisis or negative viral post?",
    "What tools do you use to schedule and analyze social posts?",
    "How do you tailor content differently for Instagram vs LinkedIn?",
    "Describe a campaign you managed and its results.",
    "How do you decide on posting frequency for a brand?",
    "How would you collaborate with influencers for a campaign?",
    "How do you measure ROI from social media efforts?",
    "How do you stay creative when producing content consistently?",
  ],
  'Content Writer': [
    "How do you research a topic you're unfamiliar with before writing?",
    "Describe your process for editing and proofreading your own work.",
    "How do you adapt your tone for different brands or audiences?",
    "How do you approach writing SEO-friendly content?",
    "Tell me about a piece of content you're especially proud of.",
    "How do you handle tight deadlines with multiple writing assignments?",
    "How do you incorporate feedback from an editor or client?",
    "What's your process for coming up with content ideas?",
    "How do you ensure consistency across a brand's content?",
    "How do you measure whether a piece of content performed well?",
  ],
  'HR Recruiter': [
    "How do you evaluate a candidate's cultural fit during an interview?",
    "Describe how you'd handle a conflict between two team members.",
    "What is your approach to sourcing candidates for a hard-to-fill role?",
    "How do you keep candidates engaged throughout a long hiring process?",
    "Describe a time you had to deliver difficult news to an employee.",
    "How do you ensure fairness and reduce bias in interviews?",
    "How would you onboard a new remote employee effectively?",
    "What HR metrics do you track regularly, and why?",
    "How do you handle a high employee turnover situation?",
    "How do you stay updated on labor laws and HR best practices?",
  ],
  'Virtual Assistant': [
    "How do you manage multiple clients' schedules at the same time?",
    "Describe your process for organizing and prioritizing daily tasks.",
    "How do you handle a client who is unclear about their requirements?",
    "What tools do you use for task and time management?",
    "How do you maintain confidentiality when handling sensitive information?",
    "Describe a time you solved a problem without direct supervision.",
    "How do you handle communication across different time zones?",
    "What steps do you take to ensure accuracy in repetitive tasks?",
    "How do you handle a sudden increase in workload?",
    "How do you keep clients updated on the status of ongoing tasks?",
  ],
};