// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCol89jO31kcBUVyIoYD9jz6yj4lFwpvdI',
    appId: '1:1038016249143:web:0728477e295adab302eeb2',
    messagingSenderId: '1038016249143',
    projectId: 'mockmaster-755e1',
    authDomain: 'mockmaster-755e1.firebaseapp.com',
    storageBucket: 'mockmaster-755e1.firebasestorage.app',
    measurementId: 'G-NLVRRZ6W1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBapl1PolqaTuKUB6_Ut4BBKmkoIKWMwHc',
    appId: '1:1038016249143:android:b33762775e48035a02eeb2',
    messagingSenderId: '1038016249143',
    projectId: 'mockmaster-755e1',
    storageBucket: 'mockmaster-755e1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3p1XJh45C4PCIZyeOgHRw1DqgtMsc4BA',
    appId: '1:1038016249143:ios:ef9962228716c18302eeb2',
    messagingSenderId: '1038016249143',
    projectId: 'mockmaster-755e1',
    storageBucket: 'mockmaster-755e1.firebasestorage.app',
    androidClientId: '1038016249143-00ou205nq2ai8ct9lmfl5agh6670ip6f.apps.googleusercontent.com',
    iosClientId: '1038016249143-isdmog0td497ei288mpqmobtndqdh73i.apps.googleusercontent.com',
    iosBundleId: 'com.example.mockmaster',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3p1XJh45C4PCIZyeOgHRw1DqgtMsc4BA',
    appId: '1:1038016249143:ios:ef9962228716c18302eeb2',
    messagingSenderId: '1038016249143',
    projectId: 'mockmaster-755e1',
    storageBucket: 'mockmaster-755e1.firebasestorage.app',
    androidClientId: '1038016249143-00ou205nq2ai8ct9lmfl5agh6670ip6f.apps.googleusercontent.com',
    iosClientId: '1038016249143-isdmog0td497ei288mpqmobtndqdh73i.apps.googleusercontent.com',
    iosBundleId: 'com.example.mockmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCol89jO31kcBUVyIoYD9jz6yj4lFwpvdI',
    appId: '1:1038016249143:web:00adf9ea727612f402eeb2',
    messagingSenderId: '1038016249143',
    projectId: 'mockmaster-755e1',
    authDomain: 'mockmaster-755e1.firebaseapp.com',
    storageBucket: 'mockmaster-755e1.firebasestorage.app',
    measurementId: 'G-86GQCD9KBC',
  );
}
